# Generated by Django 3.1.7 on 2021-04-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartquefirst', '0002_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
