# Generated by Django 3.1.7 on 2021-04-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartquerest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='cab_number',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='cab_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='query',
            field=models.ManyToManyField(blank=True, default=None, to='smartquerest.Cabinet'),
        ),
    ]
